### ISSUE TITLE
第八天裡面的一個指令小問題

### ISSUE THREAD

**Issue by aac1109** [doggy8088/Learn-Git-in-30-days#14]
保哥好
正在拜讀您的大作，讀到第八天發現這段指令中

echo. > a.txt
git add .
git commit -m "Initial commit"

第一行的echo後面似乎多了一個點
或是echo和點中間少了一個空格
辛苦了，網路上看了很多東西都沒有您說的容易了解

**Comment by annbigbig** [comment]
您好
我不是保哥哦
保哥超強
我就一隻小肉腳而已…
您在讀的東西應該也不是我寫的…

LouisHuang <notifications@github.com> 於 2015年12月10日 下午2:46 寫道：

**Comment by doggy8088** [comment]
@aac1109 你所看到的 echo 與 . 中間確實不能有空格，這是在 Windows 下寫批次檔的一個特殊語法，這一段 echo. 可以輸出一個空白行。

**Comment by aac1109** [comment]
@doggy8088 原來如此，我是用mac難怪有問題，受教了感謝。
