### ISSUE TITLE
增加閱讀的便利性？

### ISSUE THREAD

**Issue by vincechang1015** [doggy8088/Learn-Git-in-30-days#15]
保哥您好,

十分感謝有您的大作，才能比較無痛學習Git~

一點建議：每日課程的最後，或許可以增加「上一日」、「下一日」的連結，能增加閱讀的便利性。

**Comment by doggy8088** [comment]
您好：

您有興趣直接透過 Fork / Pull Request 的方式幫我修改嗎？你可以順便練習一下！ :smile: 

以下有個我之前錄製過的教學影片，你可以看看：

> 如何在 GitHub 使用 Fork / Pull Request 功能 (以 VS2013 為例) 
> https://www.youtube.com/watch?v=NTLAfy6lcdQ

Thanks! :)

**Comment by vincechang1015** [comment]
OK！我來試試看～

**Comment by YueLinHo** [comment]
Fixed with PR #16.

**Comment by doggy8088** [comment]
@YueLinHo Thanks :)

**Comment by YueLinHo** [comment]
不客氣 :smiley: 

BTW, GitLab 的 merge request(MR) 可以自動 refer 到相關 issue，也可以透過 merge MR 而自動關閉 issue。Github 不知道哪天才會有。 :P
