### ISSUE TITLE
關於第三天的小疑問

### ISSUE THREAD

**Issue by tsoliangwu0130** [doggy8088/Learn-Git-in-30-days#19]
在 "在本機建立一個共用的儲存庫 (shared repository)" 的 section 下，想請問一下 "...必須先取得這個「裸儲存庫」的內容回來，這時你必須使用 git clone [REPO_URI] 指令「複製」(clone) 一份回來才行..." 中的 REPO_URI 是否是 REPO_URL 的小筆誤呢？

**Comment by doggy8088** [comment]
URI 與 URL 是兩個不同的概念喔，應該是沒有寫錯的。

URL = Uniform Resource Locator
URI =  Uniform Resource Indicator

簡單來說，URL 與 URI 都可用來代表網路上的某個位址，但是 URL 是會更明確一些，使用 URI 的話，則能夠更抽象的表達任何網址或路徑，因為 Git Repo 的網址不一定要在網路上，在本機磁碟、網路磁碟、共用空間、共用資料夾、Git URL、SSH URL、HTTPS URL 都可以，所以用 URI 會比較恰當些。

關於 URI 與 URL 的詳細說明請參考:
http://stackoverflow.com/questions/176264/what-is-the-difference-between-a-uri-a-url-and-a-urn
