### ISSUE TITLE
關於範例的指令

### ISSUE THREAD

**Issue by uopsdod** [doggy8088/Learn-Git-in-30-days#26]
有個小小建議，
目前看到第十五天，發現範例中越來越多使用alias，
雖然在【第 14 天： Git for Windows 選項設定】有介紹過相關指令，
但考慮到可能閱讀者不是從頭學到尾的人，而是在找相關訊息的人，
且對git指令還不很熟悉，如果要直接查看其中一天的文章，
可能會無法馬上明白範例的指令，在想是否還是將完整指令打出來會比較好?

只是個人目前學習的小小建議，感謝寶哥的資源，受益良多。

**Comment by doggy8088** [comment]
@uopsdod 嗯嗯，你的建議不錯！你要不要試試看用 fork + pull request 直接幫我改？
