### ISSUE TITLE
第 17 天：關於合併的基本觀念與使用方式 - 範例修正

### ISSUE THREAD

**Issue by uopsdod** [doggy8088/Learn-Git-in-30-days#28]
在救回誤刪的分支這一小節中，
範例中，救回feature用的SHA碼是用c47287e。
仔細看過後發現，應該是要git branch feature 09dc26e，
想跟保哥這邊詢問看看是否需要修正，謝謝

**Comment by YueLinHo** [comment]
補充有問題的連結 [第 17 天](https://github.com/doggy8088/Learn-Git-in-30-days/blob/8ab7f492b4db06a0a3663e35d1e9735f6b4d129c/docs/17%20%E9%97%9C%E6%96%BC%E5%90%88%E4%BD%B5%E7%9A%84%E5%9F%BA%E6%9C%AC%E8%A7%80%E5%BF%B5%E8%88%87%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F.markdown#救回誤刪的分支)

錯誤的圖:

![image](https://cloud.githubusercontent.com/assets/5831804/16182067/8c9ab864-36d4-11e6-92b3-2384c918f0e1.png)

**Comment by doggy8088** [comment]
@uopsdod 你說的沒錯，應該是 `09dc26e` 才對！ :+1: 

不知道可否請你用影像處理軟體改圖，然後直些 fork 後修改文章內容，再發 pull request 回來呢？

**Comment by Maschinist-LZY** [comment]
果然前辈们早就发现了这个小问题！

**Comment by doggy8088** [comment]
圖片已經更正了，因此關閉 Issue
