### ISSUE TITLE
第 18 天：修正 commit 過的版本歷史紀錄 Part 1 - 範例修正

### ISSUE THREAD

**Issue by uopsdod** [doggy8088/Learn-Git-in-30-days#29]
![a1](https://cloud.githubusercontent.com/assets/19677817/16182416/920453ce-36d8-11e6-80d0-6183b4dbddd5.png)
![a2](https://cloud.githubusercontent.com/assets/19677817/16182417/95ae318e-36d8-11e6-8c18-91037e751ed3.png)

有想要直接pull request，但發現如果改一張圖，其他圖都要跟著改，
因為他們的blob名稱會不一樣，怕時間不夠所以還是先用issue方式提出這個問題!

**Comment by YueLinHo** [comment]
補連結 [第 18 天 - 刪除最近一次的版本](https://github.com/doggy8088/Learn-Git-in-30-days/blob/8ab7f492b4db06a0a3663e35d1e9735f6b4d129c/docs/18%20%E4%BF%AE%E6%AD%A3%20commit%20%E9%81%8E%E7%9A%84%E7%89%88%E6%9C%AC%E6%AD%B7%E5%8F%B2%E7%B4%80%E9%8C%84%20Part%201%20(reset%20&%20amend).markdown#刪除最近一次的版本)

> 如果改一張圖，其他圖都要跟著改，

其它的圖應該不用跟著改，
應該修改的是文字 `git show 83a841` 改 `git show aef2a5`
而圖的內容應該類似這樣：
```
$ git show aef2a5
commit aef2a5f9c04f3505c74405433f1f51c1c30adac9
Author: Will <xxx@gmail.com>
Date:   Mon Jun 20 11:30:02 2016 +0800

    Add b.txt!

diff --git a/b.txt b/b.txt
new file mode 100644
index 0000000..56a6051
--- /dev/null
+++ b/b.txt
@@ -0,0 +1 @@
+1
\ No newline at end of file
```

**Comment by uopsdod** [comment]
我把這張圖片修改好了，
但不知道該如何把圖片放入正式編輯中的檔案?
我本有打算把圖片放入專案中，然後再連結。
但是看原本repository沒有這類資料夾，而是都從f.cloud.github上面抓圖片下來展示。
想請問上傳圖片這件事該能怎麼處理，感謝

----------------------------------------------------------------------
事實上，原本你感覺被刪除的版本，其實一直儲存在 Git 的物件儲存區(object storage)裡，也就是這筆資料一直躺在 .git\objects\ 目錄下。我們還是可以用 git show **aef2a5**取得該版本 ( 即 commit 物件 ) 的詳細資料：
![gitday18_101](https://cloud.githubusercontent.com/assets/19677817/16356551/c36e225c-3b0e-11e6-9947-dca2e5c37ea6.png)

**Comment by doggy8088** [comment]
@uopsdod 可以麻煩發個 pull request 嗎？謝謝喔！ :-)

**Comment by YueLinHo** [comment]
> 我把這張圖片修改好了，
但不知道該如何把圖片放入正式編輯中的檔案?
我本有打算把圖片放入專案中，然後再連結。
但是看原本repository沒有這類資料夾，而是都從f.cloud.github上面抓圖片下來展示。
想請問上傳圖片這件事該能怎麼處理，感謝

@uopsdod 現在圖檔都拉回這個版本庫做版控了(See #40)，我想你可以試著修正這個 issue 了。
