### ISSUE TITLE
第 24 天：使用 GitHub 遠端儲存庫 - 入門篇 -- 範例照打無法成功

### ISSUE THREAD

**Issue by uopsfof** [doggy8088/Learn-Git-in-30-days#31]
![zx1](https://cloud.githubusercontent.com/assets/19767830/16330161/cfa8324c-3a19-11e6-82c9-e62943848487.png)

在嘗試將本地已建立本版的local repo上傳至Initialied remote repo這個範例(上圖)時，
最後無法成功執行git pull origin master，顯示的原因為
"fatal: refusing to merge unrelated histories"。

我把我嘗試的步驟詳細列出來：
- 在Github建立有Initialized repository
- 在本地建立git repo，並建立一個版本：
  mkdir sandbox-initialized2
  cd sandbox-initialized2
  git init
  echo a > a.txt
  git add .
  git commit -m "Initial commit"
- 告知本地repo，remote repo的位址:
  git remote add origin https://github.com/uopsfof/learnGit03_init.git
- git push 發現沒有跟remote reposiotyr sync
  Username for 'https://github.com': uopsfof
  To https://github.com/uopsfof/learnGit03_init.git
  ! [rejected]        master -> master (non-fast-forward)
  error: failed to push some refs to 'https://github.com/uopsfof/learnGit03_init.git'
  hint: Updates were rejected because the tip of your current branch is behind
  hint: its remote counterpart. Integrate the remote changes (e.g.
  hint: 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
- git pull origin master 失敗：
  warning: no common commits
  remote: Counting objects: 5, done.
  remote: Compressing objects: 100% (4/4), done.
  remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
  Unpacking objects: 100% (5/5), done.
  From https://github.com/uopsfof/learnGit03_init
  - branch            master     -> FETCH_HEAD
  - [new branch]      master     -> origin/master<br />
    **fatal: refusing to merge unrelated histories**

**Comment by YueLinHo** [comment]
@uopsfof 從 git 2.9.0 開始預設行為不允許合併沒有共同祖先的分支。
你需要加上 `--allow-unrelated-histories` 選項。

參考 [git merge (2.9.0)](https://git-scm.com/docs/git-merge/2.9.0)
```
--allow-unrelated-histories
  By default, git merge command refuses to merge histories that do not share a common ancestor.
  ...
```
（[git merge (2.8.4)](https://git-scm.com/docs/git-merge/2.8.4) 並沒有類似以上的文字。）

**Comment by doggy8088** [comment]
可以麻煩發個 pull request 嗎？謝謝喔！ :-)

**Comment by obelisk0114** [comment]
已經發了 pull request, 不過因為 GitHub 帳號不同, git pull 和 git push 放圖很奇怪, 所以並未放圖

**Comment by doggy8088** [comment]
@obelisk0114 Thanks! 已合併! 👍
