### ISSUE TITLE
第 13 天暫存版

### ISSUE THREAD

**Issue by obelisk0114** [doggy8088/Learn-Git-in-30-days#38]
在官方文件
https://git-scm.com/docs/git-stash
看到 save 和 push 放在一起, 不過並未多著墨兩者使用時機差異, 請問兩者是差不多嗎 ?

git stash 之前若有一些檔案已經加入索引 (staged) 的話, git stash 之後也會和未被加入索引 (unstaged) 一起被還原。因此三個 parents 的第二項 "原本工作目錄所包含的索引內容", 個人覺得應該改成 "原本工作目錄所追蹤 (tracked) 的內容" 較好。若要套用已經加入索引 (staged) 而不必回溯的話, 可以加上 --keep-index 而成 git stash save --keep-index。加上 -u 可以連 untracked file 一起。

還有一個很有趣的參數, -p, 可以使用互動模式讓使用者可以看檔案更動哪些部分, 不過不能暫存 untracked file

**Comment by doggy8088** [comment]
`push` 只是 `save` 的另一個別名，是完全一樣的用法。

**Comment by doggy8088** [comment]
其實「索引中內容」就是「追蹤的內容」，我覺得你的建議不錯，我已經做出了一些調整。

**Comment by doggy8088** [comment]
`--keep-index` 與 `-p` 應該不常用，就不加入文章了，以免初學者混淆，謝啦！ 👍

**Comment by YueLinHo** [comment]
off-topic:
保哥: 問一下，你會用 git stash 嗎? (我倒是完全不用它。)

**Comment by doggy8088** [comment]
@YueLinHo 需要的時候就會用，很好用啊！ 😄
