### ISSUE TITLE
第 11 天： Git 物件的一般參照

### ISSUE THREAD

**Issue by obelisk0114** [doggy8088/Learn-Git-in-30-days#39]
在工作目錄下直接執行  `git update-ref InitialCommit <commitID>` 。之後再執行  `git update-ref -d InitialCommit` 會出現 `error: refusing to update ref with bad name 'InitialCommit'`，而且使用 `git show-ref` 也不會找到他，但是他的確在 `.git` 下面， `git cat-file -p InitialCommit` 會正確執行。

若手動刪除他，將 `update-ref` 的參照名稱改成其他的話，大部分都無法被 `update-ref -d` 找到而刪除。有一些情況可以被找到而刪除，不過 `git show-ref` 仍然找不到。

但是只要設定參照名稱時，將位置改掉，像是  `git update-ref refs/InitialCommit <commitID>` 。之後就可以正確被 `git show-ref`  找到，也可以使用 `git update-ref -d ref/InitialCommit` 來刪除。但是執行  `git update-ref -d InitialCommit` 仍然會失敗。是不是 Git 不支援尋找，而且 `.git` 目錄下也變成 "真空區" ?

**Comment by YueLinHo** [comment]
> 執行 git update-ref InitialCommit <commitID> 。之後再執行 git update-ref -d InitialCommit 會出現 error: refusing to update ref with bad name 'InitialCommit'，

實際用 GfW **2.14.1** 確實無法刪除!

`git update-ref` 是底層指令，意謂著它的選項用法會比較嚴僅，不像高級階指令會用**猜的**，例如: `master` 和 `ref/heads/master` 在高階指令會視為同一個，其實是因為高階指令把 `master` "猜"成 `refs/heads/master`。

目前追查的結果應該是在 git **2.2.0** 為了更嚴格地遵守底層指令的嚴僅性而引入的
(應該是這個 [commit](https://github.com/git/git/commit/d0f810f0bc0d6b51722b400f70c2590713f168e8))。

> 使用 git show-ref 也不會找到他

內文有提到:
```
還有，執行 git show-ref 只會顯示在 .git\refs 目錄下的那些參照，
而且不管是「一般參照」或「符號參照」都一樣
```
往前一點也有提到:
```
若要建立較為正式的參照名稱，最好加上 refs/ 開頭
```
也可參考 [git 文件](https://git-scm.com/docs/git-update-ref#_description):
```
It follows real symlinks only if they start with "refs/": 
otherwise it will just try to read them and update them as a regular file 
(i.e. it will allow the filesystem to follow them, 
but will overwrite such a symlink to somewhere else with a regular filename).
```

@obelisk0114 要不要考慮提個 PR，把所有的例子改成 `refs/` 開頭? 如此，比較不會困惑其它讀者。

**Comment by obelisk0114** [comment]
文件的圖我看好像是用 camo project 轉其他主機存放的圖片, 但是我不知道有哪些適合的主機

**Comment by YueLinHo** [comment]
> 文件的圖我看好像是用 camo project 轉其他主機存放的圖片, 但是我不知道有哪些適合的主機

@doggy8088 請問，把圖拉回這個版本庫做版控 OK 嗎? 大概像[這樣](https://github.com/YueLinHo/Learn-Git-in-30-days/commit/53d016eb9257422e572a98f653f36664649c0281)

**Comment by doggy8088** [comment]
@YueLinHo OK 喔! 👍

**Comment by doggy8088** [comment]
@obelisk0114 我當除其實是用 GitHub Issue 的貼圖功能，將剪貼簿的圖在 Textarea 輸入框按下 `Ctrl+V` 貼上，然後它會自動產生的圖片連結，我再把這個圖片連結拿來用在文章裡。事實上 Issue 都沒有被建立，只是為了上傳圖片到 GitHub 並取得連結而已。我其實當初也有點擔心，不知道上傳到 GitHub 的圖片會不會刪除，但這幾年下來，感覺應該不太會刪掉才對。 😄

**Comment by YueLinHo** [comment]
@obelisk0114 現在圖檔都拉回這個版本庫做版控了(See #40)，我想你可以試著修正這個 issue 了。

**Comment by PeterPanTW** [comment]
@doggy8088 保哥您好，想請問一個問題（已上網找過答案但嘗試過還是失敗）

正常 push commit 情況下也顯示 Successfully ，但在 Github 的 Profile 要觀測小綠點，卻只有顯示去年的紀錄沒有我今年和最近的紀錄？也就是那些綠點不見了，謝謝

**Comment by doggy8088** [comment]
@PeterPanTW **last year** 並不是 **去年** 的意思，是 **最近12個月** 的意思。

我都有看到你今年的 Commit 記錄喔，看圖：
![image](https://user-images.githubusercontent.com/88981/41303769-cc585d16-6ea0-11e8-9b18-bc814b99eee3.png)

**Comment by PeterPanTW** [comment]
@doggy8088 了解！！謝謝保哥～～
