### ISSUE TITLE
第 4 天和第 18 天的 git reset

### ISSUE THREAD

**Issue by obelisk0114** [doggy8088/Learn-Git-in-30-days#55]
第 4 天的 **重置目前的工作目錄** 裡面提到可以利用 `git reset` 重置目前工作目錄的索引狀態，使用 `git reset --hard` 工作目錄也會還原。第 18 天則又提到 `git reset --soft` 也只會重置目前工作目錄的索引狀態。這是不是說 `git reset` 和 `git reset --soft` 是一樣的 ? `git reset --soft "HEAD^"` 也可以改成 `git reset "HEAD^"` ?

**Comment by doggy8088** [comment]
其實 `git reset` 預設是 `--mixed` 模式，跟 `--soft` 不太一樣，但只有些微差異。
