### ISSUE TITLE
裸儲存庫疑問

### ISSUE THREAD

**Issue by st474ddr** [doggy8088/Learn-Git-in-30-days#56]
保哥前輩 不好意思
我有先在it邦發問
但怕您沒有再繼續使用it邦
所以轉來您github上發問
最近在裸儲存庫上一直有疑問

1.在您的"在本機建立一個共用的儲存庫 (shared repository)"中
若是我想讓該專案在此主機(本機)上可以運行
主機是不是就該採用git init 的作法
畢竟裸儲存庫沒有工作目錄

2.承上述
若上面的回答是Yes的話
我想請問何時會有只記錄版本的情況產生
那台機器純粹是記錄版本和給共同開發的人員clone用嗎?
所以會把整個專案再丟到另外一個主機運行嗎?

3.為何大多數的文章都建議遠端是用裸儲存庫開發
這是我很好奇的
其實跟前面兩個問題應該蠻類似的
主要我是不懂裸儲存庫的好處到底是什麼
他做得到的git init也做得到阿

4.git是否能夠取代ftp
目前小弟我有嘗試出這種方法
以下是步驟
1.在遠端(主機)建立一個儲存庫(非裸)
2.本地端clone下來
3.本地端修好程式push上去
4.遠端checkout 新版本(如此便會更改工作目錄的程式)
這樣既可以記錄又可以做到遠端開發的感覺
不知道這樣的流程是否正確

**Comment by doggy8088** [comment]
建議你到[這裡](https://www.facebook.com/groups/git.tw)問 Git 的問題
