### ISSUE TITLE
關於 remote 相關指令的一些細節

### ISSUE THREAD

**Issue by danny0838** [doggy8088/Learn-Git-in-30-days#9]
保哥您好，讀了您的教學，覺得頗有幫助。不過關於第 25 天的一些說明，覺得可以多介紹一點。

首先我看不太懂您談到的四種分支，你寫的「本地追蹤分支」似乎是指 git 文件中說的 remote-tracking branch (根據 `git branch -h` 對 -r 參數的介紹 "act on _remote-tracking branches_")，而 remote-tracking branch 意即「追蹤遠端的分支」，不過國人習慣頗可能譯作「遠端追蹤分支」。您說的「遠端追蹤分支」我則看不太懂是指什麼。

也許您可以提一提 `git branch -vv`，這是一種有點特別的用法，會列出本地分支及對應的遠端追蹤分支。而 `git checkut` 和 `git branch` 的 `--track` (`-t`) 參數與 `git pull` 、 `git push` 和 `git branch` 的 `--set-upstream` (`-u`) 參數感覺很容易混淆，也許可以介紹一下。

我個人在接觸 `git fetch` 、 `git pull` 、 `git push` 時，經常被各種預設情形搞混，得到非常意外的結果，如果可以進一步介紹各指令在部分省略時會有什麼行為，也許會對不熟悉的人很有幫助，比如：

```
# -- fetch
git fetch origin master:master
git fetch origin master
git fetch origin refs/notes/commit
git fetch origin
git fetch
git fetch --all

# -- pull
git pull origin master:master
git pull origin master
git pull origin
git pull
git pull --all

# -- push
git push origin my_master:master
git push origin :mybranch
git push origin master
git push origin
git push origin --all
git push origin --tags
git push origin --mirror
git push
git push --all
```

最後挑個錯字：「如果你想明確下**在(->載)**特定幾個分支就好」

**Comment by YueLinHo** [comment]
> 關於第 25 天的一些說明，覺得可以多介紹一點。

或許可以參考一下 [中文版 Pro Git 3.5](http://git-scm.com/book/zh-tw/v1/Git-%E5%88%86%E6%94%AF-%E9%81%A0%E7%AB%AF%E5%88%86%E6%94%AF) 或 [這裡](https://github.com/doggy8088/Learn-Git-in-30-days/issues/8#issuecomment-91797074)

**Comment by danny0838** [comment]
ProGit 是本好書，但畢竟不是官方寫的，有些用詞和 Git 不太一致。

就我的認識，應該是這樣分類：

1. **remote branches (遠端分支)**：遠端版本庫裡的分支，可用 `git remote show origin` 等方式看到
2. **remote-treacking branches (遠端追蹤分支)**：本地版本庫中位於 `refs/remotes/*` 的參照 (ref)，用於指示遠端分支的位置
3. **local branches (本地分支)**：本地版本庫中位於 `refs/heads/*` 的參照，又可分為
  1. **tracking branches (追蹤分支)**：有設定追蹤遠端分支的本地分支（如 `git checkout mybranch origin/master -t` 會讓 mybranch 追蹤 origin 版本庫的 master 分支）
  2. non-tracking branches (非追蹤分支)：未設定追蹤遠端分支的本地分支

這些都可以從操作 Git 時的訊息看出來，比如：

```
$ git remote show origin
* remote origin
  Fetch URL: ***************************************************
  Push  URL: ***************************************************
  HEAD branch: master
  Remote branches:
    devel  tracked
    master tracked
    test   tracked
...
```

還有：

```
$ git checkout -t upstream/test
Branch test set up to track remote branch test from upstream.
Switched to a new branch 'test'
```

可見所謂遠端分支就是指遠端版本庫裡的分支（而不是像 ProGit 說的「<s>遠端分支（remote branch）是對遠端倉庫中的分支的索引。它們是一些無法移動的本地分支</s>」），一來按描述 ProGit 說的應該是遠端追蹤分支，二來它們不是本地分支，因為只有 `refs/heads/*` 命名空間中的才是本地分支，遠端追蹤分支只能說是本地版本庫中一種特殊的參照。

再來根據：

```
$ git branch -h
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>...
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -q, --quiet           suppress informational messages
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    -u, --set-upstream-to <upstream>
                          change the upstream info
    --unset-upstream      Unset the upstream info
    --color[=<when>]      use colored output
    -r, --remotes         act on remote-tracking branches
...
```

可見 `git branch` 的 `-r` 參數是作用於遠端追蹤分支。然後：

```
$ git branch -r
  origin/HEAD -> origin/devel
  origin/devel
  origin/master
  origin/test
  upstream/devel
  upstream/master
  upstream/test
```

可見那些紅字是「遠端追蹤分支」，而非 25 日原文寫的「本地追蹤分支」。

**Comment by YueLinHo** [comment]
:+1:

**Comment by YueLinHo** [comment]
找到一個 git bug, try these:
```
git branch -a
git branch -r -D -- origin/master
git branch -a
```

```git branch -r -D -- origin/master```會顯示 "Deleted **remote branch** origin/master (was xxxx)."
應該是 "Deleted **remote-tracking branch** origin/master (was xxxx)."


看來 git 本身也不太一致 :laughing:

**Comment by danny0838** [comment]
@YueLinHo Windows 上的 [Git for Windows](https://github.com/git-for-windows/git/releases) 最新有到 2.4.0 的開發版，大許分函數庫都升級了，我用了一段時間沒發現什麼大問題。您有興趣也可試試。

關於 delete remote branch 的 Bug 已回報，下一版應該會修掉。另外我發現語言包在 2012 已有簡中版，不知是否有人要搞繁中化？

**Comment by YueLinHo** [comment]
> 找到一個 git bug

@danny0838 
我才post [bug](http://git.661346.n2.nabble.com/Typo-Remote-branch-V-S-Remote-tracking-branch-tt7630076.html), 你就給了 [patch](http://git.661346.n2.nabble.com/PATCH-branch-r-d-D-should-say-quot-remote-tracking-branch-quot-tt7630077.html) :+1: 

> Windows 上的 Git for Windows 最新有到 2.4.0 的開發版...

謝謝~ 其實我一直有 flow GfW, 由於它還是開發版, 加上我目前還沒有太多時間, 所以還沒試

> 不知是否有人要搞繁中化？

我比較喜歡原文, 理解跟用起來都比較順, 比較不會有語言隔閡
語言包的部分, 有興趣的話, 或許你可以去問問看[蔣鑫](https://github.com/jiangxin)

**Comment by YueLinHo** [comment]
你用嘸蝦米?

**Comment by YueLinHo** [comment]
@danny0838 
順便說一下
Git for Windows 的維護者不喜歡人們將 msysgit 與 Git for Windows 混為一談, see [here](https://github.com/libgit2/libgit2/pull/3040#discussion_r28656649)
(簡言之, msysgit 是用來開發 Git for Windows 的開發環境)

**Comment by YueLinHo** [comment]
@danny0838 
如果你有餘力的話, 順便修一下 progit2 吧!! see [here](https://github.com/progit/progit2/issues/301)

**Comment by danny0838** [comment]
我調整了 progit2 幾處語句，但細節還要作者定奪。

另外我循線找到了 progit2 的中文化專案，想說[有幾個 Git 詞彙的翻譯可討論](https://github.com/progit/progit2-zh-tw/issues/7)，您也許會有興趣看看？

TortoiseGit 有一部分譯法個人覺得可再優化，故不太贊同 progit2 或 Git 核心之中譯沿用，不知 TortoiseGit 本身是否會考慮修改既有翻譯？

**Comment by doggy8088** [comment]
@danny0838 最近頗忙碌，幾天沒上來看，想不到討論這麼熱烈 :sweat_smile: 
想必你現在已經了解何謂「遠端追蹤分支」了！ :+1: 
錯字已修正，感謝回報！ :+1: 

另外，如果你想補充說明，歡迎你發 pull request 喔 :smiley:

**Comment by YueLinHo** [comment]
@danny0838 

> TortoiseGit 有一部分譯法個人覺得可再優化，故不太贊同 progit2 或 Git 核心之中譯沿用，不知 TortoiseGit 本身是否會考慮修改既有翻譯？

TortoiseGit 是 Open Source, 包括語言包, 所以也歡迎貢獻一自之力
它的中文化放在 Transfex 上
see https://www.transifex.com/projects/p/tortoisegit/resource/tortoisepot/
(不過要先註冊登入才看得到)
其它參考: https://code.google.com/p/tortoisegit/wiki/Translation

或者你先提出來, 或者 e-mail 給我, 或者 post issue 在 google code 上, 我可以先改

我是中途才加入 TortoiseGit 的中文化, 
TortoiseGit 繁體中文的譯詞統一性有時讓我挺費心的, 
通常我都先參考 Pro Git 怎麼翻, 然後...慢慢做

> 「測試中的 MsysGit 新版」...

Git for Windows 1.x 的時候, 其實就叫 Git for Windows 了
主開發者挺後悔在 1.x 的時候使用了 msysgit 這詞, 因為大家都混淆了
以為 msysgit 就是在 Windows 上用的 git, 其實不然, 它是拿來開發 Git for Windows 的一個開發環境
(為什麼要開發環境? 因為 Linux 上的 source 有許多沒法直接編出Windows程式, 所以需要"額外的幫助", 尤其像是 git 這種會有大量檔案操作的open source)
但是沒辦法, 許多人就是把 Git for Windows 叫成 msysgit
可能一個字比較好唸吧! 再說 Git for Windows 一點都沒有亮點的感覺
還有一個可能是它的版本號是 1.x.x.msysgit.x
所以在 2.x 的時候, 不再使用 msysgit 這個詞, 而改用 Git for Windows SDK
版本號也改成 2.x.x.windows.x
參考圖:
![history](https://cloud.githubusercontent.com/assets/5831804/7226006/fca4e21e-e776-11e4-9e68-fb7176a34fc1.png)

根據我的了解加上請益了MSYS/MSYS2的開發者畫出來的
這張圖裡面有三個團隊
一個 Cygwin, 一個 MSYS/MSYS2, 一個GfW

Cygwin 提供一個 Linux 模擬層, 讓 Linux 的程式可以在 Windwos 上跑, 但因為有模擬層, 效率不好

MSYS 是 Cygwin 的一個分支, 注重效能
它透過一些額外的 patch 讓 Linux 的 open source 可以編譯出直接在 Windows 上使用的原生執行檔
因為 MSYS 和 Cygwin 之間沒有保持同步, 所以差異越來越大, 因此又開了 MSYS2 專案, 想要盡量保持與 Cygwin 同步

GfW 則在 MSYS 的基礎上, 特別針對 git 這個單一的 Open source , 再加上一些專門為 Windows 的patch 做出 git 原生執行檔
因為 git 開始 2.x, 又有了 MSYS2, GfW 因此也打算以 MSYS2 為基礎, 重頭開始, 同時不再使用 msysgit 這個詞, 改用 Git fow Windows SDK

**Comment by danny0838** [comment]
@doggy8088 我覺得要調整的地方有點多，幾乎要重寫。目前做了點草稿，您不妨參考著用： 
https://github.com/danny0838/Learn-Git-in-30-days/commits/master

**Comment by danny0838** [comment]
@YueLinHo 我還是很混亂，[Git 官網目前放的](http://git-scm.com/download/win)是 Git for Windows 1.x 嗎？

**Comment by YueLinHo** [comment]
目前正式版最後一版是 1.9.5
2.x 還是開發版, 給相關開發者試用看看有沒有問題的

**Comment by danny0838** [comment]
意思是那個 1.9.5 是 Git for Windows ？說真的我也完全搞不清楚，尤其在 `git --version` 看到 `git version 1.9.5.msysgit.1` 實在很難不認為它是 MsysGit...XDD

**Comment by YueLinHo** [comment]
從頭至尾一直以來都叫 Git for Windows (簡稱 GfW)
但在 1.x 時, 幾乎每個人都叫它 msysgit, 
GfW 開發者非常在意用詞, 並後悔把 msysgit 字眼曝露給 final user
因此, 在 2.x 時, 就看不到 msysgit 字眼, 才讓 Git for Windows 重現江湖
(順便更新了上面的圖)

cf [What is msysGit, what is Git for Windows](https://github.com/msysgit/msysgit/wiki/What-is-msysGit,-what-is-Git-for-Windows)

**Comment by danny0838** [comment]
@YueLinHo 我想在官網的 GfW 1.9.5 的 git --version 還是秀出 msysgit 、且官網沒有明確的 "Git for Windows" 字樣的現況下，這種印象不太可能會改變的。

GfW 2.4.* 我覺得已經相當成熟，不曉得現在還列為 beta 是還有哪方面的疑慮。等它正式釋出，也許大家會比較瞭解吧。

**Comment by YueLinHo** [comment]
> 這種印象不太可能會改變的。

沒錯...

> GfW 2.4.* 我覺得已經相當成熟，不曉得現在還列為 beta 是還有哪方面的疑慮

這個你要問 https://github.com/dscho 了 :-)

**Comment by obelisk0114** [comment]
第 25 天今日小節的 git branch -r，雖然藉由 git branch -h 及親自操作可以知道是顯示遠端追蹤分支。不過文章內容並未提到，不知是否不小心被修掉了 ?

**Comment by doggy8088** [comment]
@obelisk0114 本來就沒有寫到，我只有寫到 `git branch -a` 而已，也就是顯示所有分支。
